server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "file" {
        path = "/vault/data"
      }

      seal "awskms" {
        region     = "us-east-1"
        kms_key_id = "8ddafc7c-6e03-452e-a293-23dea5cc5edc"
      }

  ha:
    enabled: false

  dataStorage:
    enabled: true
    size: 2Gi
    storageClass: gp3

  auditStorage:
    enabled: false

  resources:
    requests:
      cpu: 50m
      memory: 80Mi
    limits:
      cpu: 250m
      memory: 200Mi

  nodeSelector:
    workload: database

  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::205493924920:role/role-formation-ecom-vault"

ui:
  enabled: true

injector:
  enabled: false  # on utilise ESO, pas le sidecar injector
