apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
spec:
  version: 8.17.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      nodeSelector:
        agentpool: apps
      containers:
        - name: kibana
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
  http:
    service:
      spec:
        type: LoadBalancer
