# ─── Postgres Exporter ─────────────────────────────────────────────────────────
config:
  datasource:
    host: postgres-primary.prod.svc.cluster.local
    port: "5432"
    user: formation
    passwordSecret:
      name: postgres-exporter-secret
      key: password
    database: postgres
    sslmode: require

serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 30s

tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"

resources:
  requests:
    cpu: 15m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
