apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
spec:
  secretName: keycloak-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  ipAddresses:
    - "REPLACE_WITH_KEYCLOAK_LB_IP"
