apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-external-secret
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: keycloak
