controller:
  ingressController:
    installCRDs: false
    env:
      feature_gates: GatewayAlpha=true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

gateway:
  env:
    database: "off"
    nginx_worker_processes: "2"
    untrusted_lua: "on"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  proxy:
    type: LoadBalancer
    annotations: {}
    tls:
      enabled: true
