image:
  tag: b9aef07-main-20260724121725 # sha-slugbranch-timestamp
namespace: dev
replicaCount: 2
resources:
  requests:
    cpu: 50m
    memory: 350Mi
  limits:
    cpu: 500m
    memory: 512Mi
configmap:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://pgcat.dev.svc.cluster.local:5432/payment?sslmode=disable"
  LOG_LEVEL: "INFO"
  JAVA_TOOL_OPTIONS: "-Xmx256m -Xms128m"
secret:
  enabled: false
externalSecret:
  enabled: true
  vaultPath: dev/payment
ingress:
  name: payment-ingress-dev
hpa:
  minReplicas: 2
  maxReplicas: 4
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 25
      periodSeconds: 60
