image:
  tag: f48871b-main-20260825232209 # sha-slugbranch-timestamp
namespace: prod
replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 350Mi
  limits:
    cpu: 500m
    memory: 512Mi
configmap:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://pgcat.prod.svc.cluster.local:5432/payment?sslmode=disable"
  LOG_LEVEL: "INFO"
  JAVA_TOOL_OPTIONS: "-Xmx256m -Xms128m"
secret:
  enabled: false
externalSecret:
  enabled: true
  vaultPath: prod/payment
ingress:
  enabled: false
