apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    # Source 1 : chart Helm Argo Rollouts
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-rollouts
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/base/tools/argo-rollouts/argo-rollouts-values.yaml
    # Source 2 : manifests supplémentaires (RBAC Gateway API)
    - repoURL: https://github.com/mchekini-check-consulting/devops-formation-gitops.git
      targetRevision: main
      path: base/tools/argo-rollouts/manifests
      directory:
        recurse: true
    # Source 3 : ref pour $values
    - repoURL: https://github.com/mchekini-check-consulting/devops-formation-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
