apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/base/tools/ingress-nginx/ingress-nginx-prod-values.yaml
    - repoURL: https://github.com/mchekini-check-consulting/devops-formation-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
