apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/mchekini-check-consulting/devops-formation-gitops.git
    targetRevision: main
    path: base/tools/keycloak/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
