apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  sources:
    # Source 1 : chart Helm Kyverno
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: "~3"
      helm:
        valueFiles:
          - $values/base/tools/kyverno/kyverno-values.yaml
    # Source 2 : ref pour $values
    - repoURL: https://github.com/mchekini-check-consulting/devops-formation-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
