apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    # Source 1 : chart Helm metrics-server (kubernetes-sigs)
    - repoURL: https://kubernetes-sigs.github.io/metrics-server
      chart: metrics-server
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/base/tools/metrics-server/metrics-server-values.yaml
    # Source 2 : ref pour $values
    - repoURL: https://github.com/mchekini-check-consulting/devops-formation-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
