apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - name: catalog
                  repo: https://github.com/mchekini-check-consulting/devops-formation-catalog.git
                - name: order
                  repo: https://github.com/mchekini-check-consulting/devops-formation-order.git
                - name: payment
                  repo: https://github.com/mchekini-check-consulting/devops-formation-payment.git
                - name: front
                  repo: https://github.com/mchekini-check-consulting/devops-formation-front.git
          - list:
              elements:
                - env: dev
                  namespace: dev
                - env: prod
                  namespace: prod
  template:
    metadata:
      name: "{{.name}}-{{.env}}"
    spec:
      project: default
      sources:
        - repoURL: "{{.repo}}"
          targetRevision: main
          path: helm/
          helm:
            valueFiles:
              - $values/environments/{{.env}}/40-applications/{{.name}}/values.yaml
        - repoURL: https://github.com/mchekini-check-consulting/devops-formation-gitops.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
        - group: argoproj.io
          kind: Rollout
          jsonPointers:
            - /spec/replicas
        - kind: Pod
          jsonPointers:
            - /metadata/annotations/deploy.kubernetes.io~1date
            - /metadata/annotations/deploy.kubernetes.io~1source
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
