apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
          - env: prod
  template:
    metadata:
      name: "namespace-{{.env}}"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/mchekini-check-consulting/devops-formation-gitops.git
          targetRevision: main
          path: "environments/{{.env}}/00-namespaces"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.env}}"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
