apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network-policies
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
          - env: qualif
            namespace: qualif
          - env: prod
            namespace: prod
  template:
    metadata:
      name: "network-policies-{{.env}}"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/mchekini-check-consulting/devops-formation-utils.git
          targetRevision: main
          path: k8s/helm/network-policies/
          helm:
            parameters:
              - name: namespace
                value: "{{.namespace}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
