apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: postgres
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
          - env: prod
            namespace: prod
  template:
    metadata:
      name: "postgres-{{.env}}"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/mchekini-check-consulting/devops-formation-utils.git
          targetRevision: main
          path: k8s/helm/postgres/
          helm:
            valueFiles:
              - $values/environments/{{.env}}/10-operators/postgres/values.yaml
        - repoURL: https://github.com/mchekini-check-consulting/devops-formation-gitops.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
