controller:
  replicaCount: 2
  ingressClassResource:
    name: nginx-prod
    controllerValue: k8s.io/ingress-nginx-prod
  ingressClass: nginx-prod
  admissionWebhooks:
    enabled: false
  service:
    type: LoadBalancer
  nodeSelector:
    kubernetes.io/os: linux
