image:
  tag: 14426bb-main-20260827172158 # sha-slugbranch-timestamp
namespace: dev
replicaCount: 1
resources:
  requests:
    cpu: 10m
    memory: 20Mi
  limits:
    cpu: 500m
    memory: 512Mi
initContainer:
  enabled: true
  name: migrate
  command:
    - python
    - manage.py
    - migrate
    - --no-input
  env:
    - name: POSTGRES_HOST
      value: "postgres-primary.dev.svc.cluster.local"
configmap:
  DJANGO_SETTINGS_MODULE: "config.settings.local"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_HOST: "pgcat.dev.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "order"
  POSTGRES_SSLMODE: "disable"
  CORS_ALLOW_ALL_ORIGINS: "TRUE"
  LOG_LEVEL: "DEBUG"
  ENV_NAME: "prod"
secret:
  enabled: false
externalSecret:
  enabled: true
  vaultPath: dev/order
ingress:
  name: order-ingress-dev
