recommender:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 200m
      memory: 128Mi

updater:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

admissionController:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
