image:
  tag: 97f1ead-main-202607131610 # sha-slugbranch-timestamp
namespace: prod
replicaCount: 2
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
certificate:
  enabled: true
  name: front-prod-cert
  secretName: front-prod-tls
  issuer: selfsigned-issuer
  ipAddresses:
    - "40.66.61.108"
configmap:
  CATALOG: "http://98.66.248.206/api/products"
  ORDERS: "http://98.66.248.206/api/orders"
  PAYMENT: "http://98.66.248.206/api/payments"
  AUTH_ENABLED: "false"
rollout:
  enabled: true
ingress:
  enabled: true
  name: front-ingress-prod
  className: nginx-prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls:
    - secretName: front-prod-tls
  routes:
    - path: /
      pathType: Prefix
      service:
        name: front
        port: 80
hpa:
  minReplicas: 2
  maxReplicas: 4
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 25
      periodSeconds: 60
