apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-admin-secret
  namespace: sonarqube
type: Opaque
stringData:
  password: "Bx#>e7%mLc9!*NHb0GbLxk(2"
  currentPassword: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-monitoring-secret
  namespace: sonarqube
type: Opaque
stringData:
  monitoringPasscode: "LUu9zR)xiXh(MuOIot_v=ttL"
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-jdbc-secret
  namespace: sonarqube
type: Opaque
stringData:
  jdbc-password: "JGuQ*p2hk+wAmJixef6C>>?B"
