image:
  tag: 3690964-main-20260727214925 # sha-slugbranch-timestamp
namespace: prod
replicaCount: 1
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 384Mi
initContainer:
  enabled: true
  name: migrate
  command:
    - python
    - manage.py
    - migrate
    - --no-input
  env:
    - name: POSTGRES_HOST
      value: "postgres-primary.prod.svc.cluster.local"
configmap:
  DJANGO_SETTINGS_MODULE: "config.settings.prod"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_HOST: "pgcat.prod.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "order"
  POSTGRES_SSLMODE: "disable"
  CORS_ALLOW_ALL_ORIGINS: "FALSE"
  LOG_LEVEL: "INFO"
  ENV_NAME: "prod"
secret:
  enabled: false
externalSecret:
  enabled: true
  vaultPath: prod/order
ingress:
  enabled: false
