image:
  tag: 3c688e5-main-20260713135037 # sha-slugbranch-timestamp
namespace: prod
replicaCount: 2
resources:
  requests:
    cpu: 15m
    memory: 150Mi
  limits:
    cpu: 50m
    memory: 200Mi
initContainer:
  env:
    - name: DB_HOST
      value: "postgres-primary.prod.svc.cluster.local"
    - name: DB_SSL
      value: "true"
    - name: PGSSLMODE
      value: "no-verify"
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
configmap:
  DB_HOST: "pgcat.prod.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "catalogue"
  DB_SSL: "false"
  PGSSLMODE: "disable"
  CORS_ALLOW_ALL_ORIGINS: "FALSE"
  LOG_LEVEL: "WARNING"
secret:
  enabled: true
  data:
    DB_USER: formation
    DB_PASSWORD: test
ingress:
  name: catalogue-ingress-prod
rollout:
  enabled: true
  strategy:
    canary:
      trafficRouting:
        nginx:
          stableIngress: catalogue-ingress-prod
hpa:
  minReplicas: 2
  maxReplicas: 4
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 25
      periodSeconds: 60
