image:
  tag: 97f1ead-main-202607131610 # sha-slugbranch-timestamp
namespace: dev
replicaCount: 2
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
configmap:
  CATALOG: "https://98.66.248.206/api/products"
  ORDERS: "https://98.66.248.206/api/orders"
  PAYMENT: "https://98.66.248.206/api/payments"
  AUTH_ENABLED: "true"
  KEYCLOAK_URL: "https://51.11.203.15"
  KEYCLOAK_REALM: "formation"
  KEYCLOAK_CLIENT_ID: "frontend-app"
certificate:
  enabled: true
  name: front-dev-cert
  secretName: front-dev-tls
  issuer: selfsigned-issuer
  ipAddresses:
    - "98.66.248.206"
ingress:
  enabled: true
  name: front-ingress-dev
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls:
    - secretName: front-dev-tls
  routes:
    - path: /
      pathType: Prefix
      service:
        name: front
        port: 80
hpa:
  minReplicas: 2
  maxReplicas: 4
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 25
      periodSeconds: 60
