image:
  tag: 28d633c-main-202607202150 # sha-slugbranch-timestamp
namespace: dev
replicaCount: 2
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
configmap:
  CATALOG: "https://a76e1394f9b474a11bf71d91e5cfd3ef-616597816.us-east-1.elb.amazonaws.com/api/products"
  ORDERS: "https://a76e1394f9b474a11bf71d91e5cfd3ef-616597816.us-east-1.elb.amazonaws.com/api/orders"
  PAYMENT: "https://a76e1394f9b474a11bf71d91e5cfd3ef-616597816.us-east-1.elb.amazonaws.com/api/payments"
  AUTH_ENABLED: "true"
  # TODO: remplacer par le hostname ELB reel de Keycloak une fois deploye sur EKS
  KEYCLOAK_URL: "https://k8s-keycloak-keycloak-4064f01ea2-9337af193f3f2306.elb.us-east-1.amazonaws.com"
  KEYCLOAK_REALM: "formation"
  KEYCLOAK_CLIENT_ID: "frontend-app"
certificate:
  enabled: true
  name: front-dev-cert
  secretName: front-dev-tls
  issuer: selfsigned-issuer
  dnsNames:
    - "a76e1394f9b474a11bf71d91e5cfd3ef-616597816.us-east-1.elb.amazonaws.com"
ingress:
  enabled: true
  name: front-ingress-dev
  className: kong
  annotations: {}
  tls:
    - secretName: front-dev-tls
  routes:
    - path: /
      pathType: Prefix
      service:
        name: front
        port: 80
hpa:
  minReplicas: 2
  maxReplicas: 4
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 25
      periodSeconds: 60
