image:
  tag: f6198be-main-20260827200433 # sha-slugbranch-timestamp
namespace: dev
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
configmap:
  CATALOG: "https://shop.check-consulting.net/api/products"
  ORDERS: "https://shop.check-consulting.net/api/orders"
  PAYMENT: "https://shop.check-consulting.net/api/payments"
  AUTH_ENABLED: "true"
  KEYCLOAK_URL: "https://keycloak.check-consulting.net"
  KEYCLOAK_REALM: "formation"
  KEYCLOAK_CLIENT_ID: "frontend-app"
certificate:
  enabled: true
  name: front-dev-cert
  secretName: front-dev-tls
  issuer: selfsigned-issuer
  dnsNames:
    - "a76e1394f9b474a11bf71d91e5cfd3ef-616597816.us-east-1.elb.amazonaws.com"
ingress:
  enabled: true
  name: front-ingress-dev
  className: kong
  annotations: {}
  tls:
    - secretName: front-dev-tls
  routes:
    - path: /
      pathType: Prefix
      service:
        name: front
        port: 80
