global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/keycloak

auth:
  adminUser: admin
  existingSecret: keycloak-secret
  passwordSecretKey: KEYCLOAK_ADMIN_PASSWORD

postgresql:
  enabled: false

externalDatabase:
  host: pgcat.dev.svc.cluster.local
  port: 5432
  user: keycloak
  database: keycloak
  existingSecret: keycloak-secret
  existingSecretPasswordKey: KEYCLOAK_DB_PASSWORD

service:
  type: LoadBalancer

tls:
  enabled: true
  existingSecret: keycloak-tls

ingress:
  enabled: false

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    memory: 1Gi

keycloakConfigCli:
  enabled: true
  existingConfigmap: keycloak-realm-config
  image:
    registry: docker.io
    repository: bitnamilegacy/keycloak-config-cli
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
