# Mode par defaut : Audit (ne bloque pas, genere des PolicyReports)
validationFailureAction: Audit

# Namespaces ou les policies sont en mode Enforce (bloquant)
enforceNamespaces: [prod]

# Namespaces systeme exclus des policies
excludeNamespaces:
  - kube-system
  - kyverno
  - argocd
  - ingress-nginx
  - sonarqube
  - calico-system
  - tigera-operator
  - vault
  - external-secrets
  - reloader
  - cert-manager
  - keycloak
  - istio-system
  - kong
  - monitoring

# Registries autorises
allowedRegistries:
  - "docker.io/library/*"
  - "docker.io/bitnami/*"
  - "ghcr.io/*"
  - "registry.k8s.io/*"
  - "quay.io/*"
  - "*.azurecr.io/*"
  - "docker.io/bitnamilegacy/*"
  - "docker.io/istio/*"
  - "registry.istio.io/*"
  - "docker.io/pgedge/*"
  - "docker.io/alpine/*"
  - "docker.io/kong/*"
  - "docker.io/grafana/*"
  - "docker.io/jimmidyson/*"

# Labels obligatoires
requiredLabels:
  - "app.kubernetes.io/name"
  - "app.kubernetes.io/managed-by"
