# Mode par defaut : Audit (ne bloque pas, genere des PolicyReports)
validationFailureAction: Audit

# Namespaces ou les policies sont en mode Enforce (bloquant)
enforceNamespaces: [prod]

# Namespaces systeme exclus des policies
excludeNamespaces:
  - kube-system
  - kyverno
  - argocd
  - ingress-nginx
  - sonarqube
  - calico-system
  - tigera-operator
  - vault
  - external-secrets
  - reloader

# Registries autorises
allowedRegistries:
  - "docker.io/library/*"
  - "docker.io/bitnami/*"
  - "ghcr.io/*"
  - "registry.k8s.io/*"
  - "quay.io/*"
  - "*.azurecr.io/*"

# Labels obligatoires
requiredLabels:
  - "app.kubernetes.io/name"
  - "app.kubernetes.io/managed-by"
