image:
  tag: 444c582-main-20260710124355 # sha-slugbranch-timestamp
namespace: qualif
replicaCount: 2
resources:
  requests:
    cpu: 15m
    memory: 150Mi
  limits:
    cpu: 50m
    memory: 200Mi
initContainer:
  env:
    - name: DB_HOST
      value: "postgres-primary.qualif.svc.cluster.local"
    - name: DB_SSL
      value: "true"
    - name: PGSSLMODE
      value: "no-verify"
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
configmap:
  DB_HOST: "pgcat.qualif.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "catalogue"
  DB_SSL: "false"
  PGSSLMODE: "disable"
  CORS_ALLOW_ALL_ORIGINS: "FALSE"
  LOG_LEVEL: "INFO"
secret:
  enabled: true
  data:
    DB_USER: formation
    DB_PASSWORD: test
hpa:
  minReplicas: 2
  maxReplicas: 4
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 25
      periodSeconds: 60
