tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"

pilot:
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      memory: 384Mi
  env:
    PILOT_ENABLE_AMBIENT: "true"

meshConfig:
  accessLogFile: /dev/stdout
