crds:
  install: true

admissionController:
  replicas: 0
  resources:
    limits:
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi

backgroundController:
  replicas: 0
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi

cleanupController:
  replicas: 0
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi

reportsController:
  replicas: 0
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
