crds:
  install: true

admissionController:
  replicas: 1
  resources:
    limits:
      memory: 384Mi
    requests:
      cpu: 10m
      memory: 20Mi

backgroundController:
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 20Mi

cleanupController:
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 20Mi

reportsController:
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 20Mi
