crds:
  install: true

admissionController:
  replicas: 1
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"
  resources:
    limits:
      memory: 384Mi
    requests:
      cpu: 25m
      memory: 128Mi

backgroundController:
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 64Mi

cleanupController:
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 64Mi

reportsController:
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 64Mi
