{
 "title": "Dashboard-Metrics-Applicatives",
 "tags": [
  "applicative",
  "order",
  "payment",
  "catalog"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Payment And Order", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commandes créées / Payments échoués",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(orders_created_total{namespace=\"prod\"})",
     "legendFormat": "Commandes créées"
    },
    {
     "expr": "sum(payments_failed_total{namespace=\"prod\"})",
     "legendFormat": "Paiements échoués"
    }
   ]
  },
  {
   "title": "Taux d'échec paiement (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(payments_failed_total{namespace=\"prod\"})\n  /\n  (sum(payments_success_total{namespace=\"prod\"}) + sum(payments_failed_total{namespace=\"prod\"}))\n  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence P95 Order",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=\"prod\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence P95 Payment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=\"prod\", job=\"payment\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux d'erreur HTTP 5xx (%)  ORDER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total_by_status_total{namespace=\"prod\", status=~\"5..\"}[5m]))/sum(rate(django_http_responses_total_by_status_total{namespace=\"prod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux d'erreur HTTP 5xx (%) Payment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"prod\", job=\"payment\", status=~\"5..\"}[5m])) or vector(0)\n  /\n  sum(rate(http_server_requests_seconds_count{namespace=\"prod\", job=\"payment\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Taux d'erreur HTTP 5xx (%) Catalog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=\"prod\", job=\"catalogue\", status_code=~\"5..\"}[5m])) or vector(0)\n  /\n  sum(rate(http_request_duration_seconds_count{namespace=\"prod\", job=\"catalogue\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence P95 Catalog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{namespace=\"prod\", service=\"catalogue\"}[5m])) by(le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}