{
 "title": "Dashboard Kong And Postgres Metrics",
 "tags": [
  "kong",
  "postgresql",
  "overview"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Visual PostgresSql", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cache hit ratio par base",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_hit[5m])) by (datname)\n  /\n  (sum(rate(pg_stat_database_blks_hit[5m])) by (datname) + sum(rate(pg_stat_database_blks_read[5m])) by (datname))\n  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connexion par état",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count) by (state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pourcentage d'utilisation des connexions PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count) / sum(pg_settings_max_connections) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pourcentage de connexions PostgreSQL  (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count)\n  /\n  sum(pg_settings_max_connections)\n  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit ratio PostgreSQL global",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_hit[5m]))\n  /\n  (sum(rate(pg_stat_database_blks_hit[5m])) + sum(rate(pg_stat_database_blks_read[5m])))\n  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connexions PostgreSQL actives",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "sum(pg_stat_activity_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lag de réplication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "pg_replication_lag_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connexions actives par base",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Visual Kong", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "KONG Latence P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket[5m])) by (le, service))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requêtes par seconde Kong",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total[5m])) by (service, code)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Cache hit ratio Kong",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total[5m])) by (service, code)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}